### ISSUE TITLE
enabling LifeStealZ 1.1.28 error

### ISSUE THREAD

**Issue by TheodoreMeyer** [KartoffelChipss/LifeStealZ#24]
**Describe the bug**
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
[14:58:18] [Server thread/ERROR]: Error occurred while enabling LifeStealZ v1.1.28 (Is it up to date?)
java.lang.NoClassDefFoundError: net/kyori/adventure/text/Component
        at org.strassburger.lifestealz.util.CommandManager.registerCommands(CommandManager.java:18) ~[?:?]
        at org.strassburger.lifestealz.LifeStealZ.onEnable(LifeStealZ.java:44) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugin(CraftServer.java:575) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4300-Spigot-a759b62-7070de8]
        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugins(CraftServer.java:489) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4300-Spigot-a759b62-7070de8]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4300-Spigot-a759b62-7070de8]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:426) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4300-Spigot-a759b62-7070de8]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:269) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4300-Spigot-a759b62-7070de8]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1017) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4300-Spigot-a759b62-7070de8]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4300-Spigot-a759b62-7070de8]
        at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]
Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.text.Component
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:160) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:112) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        ... 13 more
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
**To Reproduce**
1. Run lifestealz 1.1.28 with spigot 1.21
2. watch thread during server startup

**Expected behavior**
The error to not appear and to be able to interact with plugin normally

**Screenshots**
None

**Server Setup**
 - Server Software: Spigot 1.21.1
 - Minecraft Version: 1.21
 - Plugin Version: 1.1.28

**Additional context**
it says lifestealz is running, but can't interact with it (no commands work)
everything else for the plugin works
Comes up around 90% of the time.

**Comment by KartoffelChipss** [comment]
You need to use PaperMC or any fork of Paper

**Comment by TheodoreMeyer** [comment]
I downloaded this off spigot (https://www.spigotmc.org/resources/lifestealz.111469/)
so i don't know why its there when its not supported.

**Comment by KartoffelChipss** [comment]
Because it's a plugin for Minecraft servers?

**Comment by KartoffelChipss** [comment]
Paper and Purpur are based on Spigot and use part of the same api

**Comment by KartoffelChipss** [comment]
And next time please use the [Discord](https://strassburger.org/discord) for support related stuff.
