### ISSUE TITLE
Revive crystal not destroyed upon use

### ISSUE THREAD

**Issue by JerichoTorrent** [KartoffelChipss/LifeStealZ#38]
**Describe the bug**
When a player uses a revive crystal the crystal is not removed, allowing for infinite reviving

**To Reproduce**
1. Craft revive crystal
2. Use it infinitely

**Expected behavior**
The revive crystal is destroyed upon use

**Screenshots**
No screenshots but do have this error:
```
[04:58:19 ERROR]: Could not pass event InventoryClickEvent to LifeStealZ v2.7.2
org.bukkit.command.CommandException: Unhandled exception executing command 'lifestealz' in plugin LifeStealZ v2.7.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:1001) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:1114) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at lifestealz-2.7.2.jar/org.strassburger.lifestealz.listeners.InventoryClickListener.onInventoryClick(InventoryClickListener.java:113) ~[lifestealz-2.7.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1049.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-21-cfa3c61]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3225) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1542) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1519) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1512) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1471) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1478) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1323) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getAttribute(org.bukkit.attribute.Attribute)" because "player" is null
        at lifestealz-2.7.2.jar/org.strassburger.lifestealz.LifeStealZ.setMaxHealth(LifeStealZ.java:167) ~[lifestealz-2.7.2.jar:?]
        at lifestealz-2.7.2.jar/org.strassburger.lifestealz.commands.SettingsCommand.handleHearts(SettingsCommand.java:239) ~[lifestealz-2.7.2.jar:?]
        at lifestealz-2.7.2.jar/org.strassburger.lifestealz.commands.SettingsCommand.onCommand(SettingsCommand.java:58) ~[lifestealz-2.7.2.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        ... 29 more
[04:58:19 INFO]: [Not Secure] [Server] &aDarkestclaws0 revived BossZoroark!
```

**Server Setup**
 - Server Software: Pufferfish
 - Minecraft Version: 1.21.1
 - Plugin Version: 2.7.2

**Additional context**
Not gonna lie this revive crystal did NOT work from the default config and it has been a struggle to get it to work properly.

**Comment by abb3v** [comment]
... yikes

**Comment by JerichoTorrent** [comment]
Yeah big yikes. Here's some more issues I've had with default config:
- Revive crystals not working at all
- Players not getting banned when they should (permanently stay at 0 hearts)
- when revived, players are not unbanned nor do revivecrystals get removed or do anything
- players don't get any hearts when revived
Current config after extensive testing and bug reports from my community:
```
- "tempban &player& 1d server:Lifesteal"

heartuseCommands:
# - "say &player& used a heart item"

reviveuseCommands:
- "say &a&player& revived &target&!"
- "unban &player&"
- "lifestealz hearts set &target& 5"
```

**Comment by KartoffelChipss** [comment]
I'm sorry, but we currently don't support Pufferfish. It might be a problem with that server software.

**Comment by KartoffelChipss** [comment]
Or when I have a look at the part of your config file, that you provided it is maybe a misconfiguration on your side

**Comment by JerichoTorrent** [comment]
Pufferfish is just a fork of paper with some extra optimizations? It makes no changes to any code that would have any effect or incompatibility with your plugin. Any plugin that works on a paper server will work on pufferfish.
You don't have to target pufferfish in any way.

**Comment by KartoffelChipss** [comment]
Then you probably misconfigured your plugin. Would you mind sending me your config files? We could also switch to the Discord to make conversation a bit easier: https://strassburger.org/discord

**Comment by JerichoTorrent** [comment]
Kartoffel. I was using the default config when revive crystals didn't work at all, so that's incorrect. I have also shared the only part of the config I changed, so please, if you believe it is a misconfiguration you can see it and tell me what I did wrong.

**Comment by KartoffelChipss** [comment]
What exactly do you mean by "didn't work at all"?
Your configuration here (if the rest is default) makes no sense. You cannot have the default LSZ ban system and implement your own ban system at the same time.
And If you want to have players revive with a specific amount of hearts, use the "reviveHearts" option and not a weird hack with the revive commands.

**Comment by Skullians** [comment]
Surely the ban system is irrelevant?
The ban system should have no impact whatsoever on the revive system.
The issue at hand is the failure to remove the revive crystal.

**Comment by Skullians** [comment]
`Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getAttribute(org.bukkit.attribute.Attribute)" because "player" is null`

This is not a ban-system related issue.

**Comment by KartoffelChipss** [comment]
Please if you don't know how the plugin works, don't try to analyze this.
The revive system is the ban system. If you want your own, you have to set the "disablePlayerBanOnElimination" option to false.
And yes, I know how to read an error message thanks.
