### ISSUE TITLE
Withdrawing a heart results in an unexpected error

### ISSUE THREAD

**Issue by SkyKingPX** [KartoffelChipss/LifeStealZ#39]
**Describe the bug**
Title ^

**To Reproduce**
1. Run the command /withdrawheart
2. See error

**Expected behavior**
It should give the player a heart item

**Server Setup**
 - Server Software: PaperMC
 - Minecraft Version 1.21.1
 - Plugin Version 2.9.0

**Additional context**
Error:
```
[18:02:11 ERROR]: Command exception: /withdrawheart
org.bukkit.command.CommandException: Unhandled exception executing command 'withdrawheart' in plugin LifeStealZ v2.9.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.3.10.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:30) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:451) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.commands.Commands.performCommand(Commands.java:358) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.commands.Commands.performCommand(Commands.java:345) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.commands.Commands.performCommand(Commands.java:340) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2297) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$15(ServerGamePacketListenerImpl.java:2271) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1581) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1558) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1551) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1510) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1517) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1362) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: Name is null
        at java.base/java.lang.Enum.valueOf(Enum.java:291) ~[?:?]
        at org.bukkit.Material.valueOf(Material.java:134) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at lifestealz-2.9.0.jar/org.strassburger.lifestealz.util.customitems.CustomItemManager.createCustomItem(CustomItemManager.java:36) ~[lifestealz-2.9.0.jar:?]
        at lifestealz-2.9.0.jar/org.strassburger.lifestealz.util.customitems.CustomItemManager.createHeart(CustomItemManager.java:74) ~[lifestealz-2.9.0.jar:?]
        at lifestealz-2.9.0.jar/org.strassburger.lifestealz.commands.WithdrawCommand.onCommand(WithdrawCommand.java:120) ~[lifestealz-2.9.0.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        ... 27 more
```

**Comment by KartoffelChipss** [comment]
Could you provide your `config.yml` and `items.yml` file?

**Comment by SkyKingPX** [comment]
That was fast...
Of course:
[config.zip](https://github.com/user-attachments/files/18186697/config.zip)

**Comment by KartoffelChipss** [comment]
![CleanShot 2024-12-18 at 18 23 55@2x](https://github.com/user-attachments/assets/771107fd-f5ae-4414-bbb4-0119cd2773d6)
In your config.yml you set the heart item to an item with the id `heart`, but in your items.yml file, there is not item with that id. So either set `heartItem` in the config.yml back to `defaultheart` or actually add an item with the id `heart` to the items.yml file

**Comment by SkyKingPX** [comment]
Thank you and sorry to bother.

**Comment by KartoffelChipss** [comment]
No problem :)
